### ISSUE TITLE
Type Error: Array.from() is not a function

### ISSUE THREAD

**Issue by PriyankBhatt** [colinf/react-easy-select#1]
I am using browserify to bundle, so as to render it on client side.

```
var React = require('react');
var EasySelect = require('react-easy-select');
React.render(
       React.createElement(EasySelect, {name: "ex1", options: ["HELLO","WORLD"], onChange: handleChange}),
       document.getElementById("element")
);
function handleChange(change) {
    console.log("HELLO");
}
```

But javascript gives me an error stating that Array.from() is not a function.

**Comment by colinf** [comment]
Hi Priyank, react-easy-select is written using a fair bit of ES6 syntax including Array.from - so you need to use the babelify transform as part of your browserify build. And also import (or require) "babelify/polyfill".

If you look at gulpfile.js in the root directory of react-easy-select, the build/example task shows an example of using babelify. And in src/example/example-app.js the first line imports the polyfill.

Let me know if this doesn't work and I'll investigate further.

Cheers,
  Colin
